### PR TITLE
Implement Clone for several public data structures

### PR DESCRIPTION
**Pull request by fmease**

### CODE REVIEW

**Comment by dbyr** [comment]
I'm fine with adding Clone, however I feel like there is the possibility for the others to back-fire due to the nature of the red-black tree. For example, there are multiple representations for a tree containing the exact same items (for the simplest example, take a tree containing 1 and 2, either element could be the root of the tree depending on the order of insertion). I'm not overly familiar with how the derive macro applies the equality traits (I'll try and find out) but I would assume it would compare on a bit-by-bit basis? Or perhaps recursively on all contained members of a data structure? In either case two trees that "seem" equal (like mentioned before) wouldn't always be considered equal by the operator.
Like I said, I'll investigate the derived implementations. Otherwise if you have any suggestions or thoughts let me know.

**Comment by eadf** [comment]
One of the advantages of this library compared to the std::collection structures is that this library can key on float without workarounds like `OrderedFloat`. Adding `Eq` and `Ord` would mean I have to add some ugly float wrappings, adding `Hash` would be a game breaker.

Also, I see you added derive Hash on the data structures but not require Hash on K,V or T. Does that even work?

**Comment by fmease** [comment]
Yeah, you two are right. I wasn't thinking straight when I was proposing to add this. Now it's only `Clone`.
I wonder if it is possible to write a custom `PartialEq`/… implementation which does not leak private information or breaks any invariants.

**Comment by dbyr** [comment]
Thanks for updating that. I can look into PartialEq, I have a feeling it should be possible, though probably not the most efficient. If it should behave the way I'm thinking it can probably done in O(n) time.
> Also, I see you added derive Hash on the data structures but not require Hash on K,V or T. Does that even work?

I was curious about that too, I thought it was strange... The build was passing so it was at least compiling. Perhaps the derive macro only implements under the condition that any generics meet some sort of requirement like `impl<T> Hash for RBTree<T> where T: Hash` for example?

**Pull request merged**
