### PR TITLE
Add serde derives

### LINKED ISSUE #15: serialize & deserialize
add feature serde

### PR DESCRIPTION
**Pull request by eadf**
Fix #15
Hope you don't mind, but I'm piggy-backing the serve tests on existing test

### CODE REVIEW

**Comment by eadf** [comment]
CI clippy fails, but it is not in any code I've touched:
```
error: all if blocks contain the same code at the end
11         --> src/node.rs:487:9
12         |
13 487 | /             if doubled {
14 488 | |                 Doubled(tmp.gut().value)
15 489 | |             } else {
16 490 | |                 Removed(tmp.gut().value)
17 491 | |             }
18 492 | |         }
19         | |_________^
```
Guess clippy has been updated since last checkin.
Interesting, this clippy test only fails on stable, not on nightly.

**Comment by eadf** [comment]
I could squash all of this edits into one commit, if you like

**Comment by eadf** [comment]
I'm not exactly sure about how this works, but I suspect that I'm not allowed to alter `.github/workflows` files.
So here is a diff of the changes in workflow that will test all features:
```
$ git diff
diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
index cd227f8..aa202f9 100644
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -17,9 +17,9 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: Build
-      run: cargo build --verbose
+      run: cargo build --verbose --all-features
     - name: Run tests
-      run: cargo test --verbose
+      run: cargo test --verbose --all-features
 
   lint:
 
@@ -40,4 +40,4 @@ jobs:
       - uses: actions-rs/cargo@v1
         with:
           command: clippy
-          args: -- -D warnings
+          args: --all-features -- -D warnings
```

**Review by dbyr — APPROVED** [review]
Thanks for the changes, I'll upload a new version once soon

**Pull request merged**
